#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export path_root=$(mktemp --directory)

mkdir -p ${path_root}/boot/overlays

cat "${SCRIPTPATH}/config.txt" > "${path_root}/boot/config.txt"

exitcode=0

function test {
    if [ $? -eq 0 ]; then
        echo -e "\e[32m[PASS]\e[0m""[$1]" "${@:2}"
    else
        echo -e "\e[31m[FAIL]\e[0m""[$1]" "${@:2}"
        exitcode=1
    fi
}

function testForErrors {
    file "${path_root}/boot/overlays"/* | grep --silent "boot CPU=0"
    test "$@" "Overlay installed into /boot/overlays/" 

    diff -u "${SCRIPTPATH}/config.txt" "${path_root}/boot/config.txt" |  grep --silent "+dtoverlay=tft35a"
    test "$@" "/boot/config.txt edit for dtoverlay" $@
}

if [ -f ${SCRIPTPATH}/../install ]; then
    "${SCRIPTPATH}/../install" tft35a
    testForErrors  "offline"
fi

curl -o- https://raw.githubusercontent.com/Alicetech/rpi-lcd-show-improved/main/install | SCRIPTPATH=/dev/null bash /dev/stdin tft35a
testForErrors "online"

# find "${path_root}" -exec file {} \;

rm -r "${path_root}"

[ ${exitcode} -eq 0 ] || exit ${exitcode}