#!/bin/bash

temp_dir=$(mktemp --directory)
export path_root_boot_config_txt="${temp_dir}/config.txt"
export path_root_boot_overlays="${temp_dir}"

cat config.txt > "${path_root_boot_config_txt}"

../LCD35-show

echo ================================== 
echo == HERE IS THE TEST OUTCOME:
echo ==
echo 

diff -u config.txt "${temp_dir}/config.txt"

ls -al "${temp_dir}"
rm -r "${temp_dir}"